import * as app from './app';

test.todo('Commander');

test('Should return early and fail for invalid domains', async () => {
  console.error = jest.fn();

  await app.scrape('notadomainname');

  expect(console.error).toHaveBeenCalledWith('Invalid domain name');
});

test('Should fetch homepage for valid domain', async () => {
  await app.scrape('www.example.com');
});

test('Should allow domain with protocol', async () => {
  await app.scrape('https://www.example.com');
});

test('Complex site with many links', async () => {
  const output = await app.scrape('https://www.sedna.com');
  expect(output).toMatchObject(expectedSitemap);
});

test('Should never scrape same page twice', async () => {
  const spy = jest.spyOn(app, 'extractLinks');
  await app.scrape('https://www.sedna.com');
  const scrapedUrls = spy.mock.calls.map((call) => call[0].href);
  expect(scrapedUrls.length === new Set(scrapedUrls).size).toBe(true);
});

const expectedSitemap = {
  'https://sedna.com': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/product-overview-download',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/solutions/connected',
    'https://sedna.com/company/leadership-team',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
  ],
  'https://sedna.com/features': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/solutions/enterprise-collaboration': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/solutions/connection': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/solutions/intelligence': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/solutions/speed': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/company/leadership': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/contact': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
    'https://sedna.com/request-demo',
  ],
  'https://sedna.com/solutions/collaboration': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/request-demo': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
    'https://sedna.com/request-demo',
  ],
  'https://sedna.com/terms-of-service': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/support',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/privacy-notice': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/product-overview': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
    'https://sedna.com/request-demo',
  ],
  'https://sedna.com/company/leadership-team': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/company/leadership-team',
  ],
  'https://sedna.com/support': [],
  'https://sedna.com/product-overview-download': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
    'https://sedna.com/request-demo',
  ],
  'https://sedna.com/solutions/connected': [
    'https://sedna.com',
    'https://sedna.com/features',
    'https://sedna.com/solutions/enterprise-collaboration',
    'https://sedna.com/solutions/connection',
    'https://sedna.com/solutions/intelligence',
    'https://sedna.com/solutions/speed',
    'https://sedna.com/company/leadership',
    'https://sedna.com/contact',
    'https://sedna.com/request-demo',
    'https://sedna.com/product-overview',
    'https://sedna.com/solutions/collaboration',
    'https://sedna.com/terms-of-service',
    'https://sedna.com/privacy-notice',
    'https://sedna.com/company/leadership-team',
  ],
};
